# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application

on:
  push:
    branches: [ master ]
  schedule:
    - cron: '33 22 * * *'
    - cron: '13 0 * * *'
    - cron: '49 2 * * *'
    - cron: '7 6 * * *'
    - cron: '37 8 * * *'
    - cron: '55 10 * * *'
    - cron: '01 13 * * *'
    - cron: '33 13 * * *'
    - cron: '22 14 * * *'
    - cron: '22 2 * * *'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests
        pip install beautifulsoup4
        pip install lxml
        wget https://raw.githubusercontent.com/zsqw123/cdn/master/prj/autoHealth/actions.py
    - name: Run
      run: |
        python actions.py ${{ secrets.NUM }} ${{ secrets.PWD }}
